name: diagram_editor
description: A flutter diagram editor library that provides DiagramEditor widget and a possibility to customize all editor design and behavior.
version: 0.1.9
homepage: https://arokip.github.io/fdl_demo_app
repository: https://github.com/Arokip/flutter_diagram_editor

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
